name = "lean-mathlib-1stproj"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["lean-mathlib-1stproj", "LeanMathlib1stproj"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LeanMathlib1stproj"

[[lean_exe]]
name = "lean-mathlib-1stproj"
root = "Main"
